apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nextjs-blog-template
  title: NextJS Blog Template
  description: Create a website powered with Next.js
  tags:
    - recommended
    - react
    - nextjs
spec:
  owner: support@venue.sh
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        environment:
          title: Environment
          description: Client Environment
          type: string
          default: dev
          enum:
            - dev
            - staging
            - production
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        defaultBranch:
          title: Default Branch
          description: Sets the default branch on the repository. The default value is main.
          type: string
          default: "main"

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          environment: ${{ parameters.environment }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: vercel
      name: Create Vercel Project
      action: vercel:project:create
      input:
        component_id: ${{ parameters.component_id }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: ${{ parameters.defaultBranch }}
        secrets:
          VERCEL_ORG_ID: ${{ steps.vercel.output.vercelOrgId }}
          VERCEL_PROJECT_ID: ${{ steps.vercel.output.vercelProjectId }}
          VERCEL_TOKEN: ${{ steps.vercel.output.vercelToken }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Vercel Project
        url: ${{ steps.vercel.output.vercelProjectUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
